language: python
python:
- '3.6'
script: tests/verify-yaml.sh
deploy:
- provider: script
  script: bash tests/deploy-centos-ci.sh
  on:
    branch: master
env:
  global:
  - secure: 0oyema58r8TYiL6t9zG8ClKWC8N5f6PV/HRI2+HMswmINMvZGt7pvcyL4Yl4UMK12M8cIKqA1neDvs3Wn3SCf76wWmw+62VAGGKZ02laUmOj2/kSp7hFd1PxvYI1AN6hSV4wgj+ctBockGwXxKkmJkSIrDTUSd+IE3vRE0g09MDSKIYFYjPrVIN0hdF5qjbLLz0VmYpUvoBTleDrLkfC8aPGNjy+WVylXxaPhHItO2/ozMbe97u9uxVSJ0oSHEy2k+WFK07Op66qE/fvc5f3TpGfPCm2ZTXPKEgaNqa2MKsHWxFjqttn36xmf1Cv4ma6oceg9WDGe79fIjS/frou48ZrLSmaDPeO+GuOhMBpH4QiXhyXe4qeSutLwuRHbm7zq3gZTg25ybGkapWqMaeMIGXHSBRo2k7SawO/rzh4VsJnxyn8oE6XqEd5u6Jkvidz94YUVnp6RGJFKoYE8u6o4GFtQh6OQLTYikq0XHVW0tRjtdu56wgK8amvUr78mmhq989PA1iMsPfzduqs29jnzOz/kpIuo6stbI8iKtxVONnOe0l0tWKrFs/cDHaTgofSwuKXklwkgrHCHKBDJ0B1knpFguXHzj6ahpmknJUpTpl2XTddDrqiWxdJrEuMUA925CptPe5o1mubeq9rrt7xgZKMMbLv2FzcDhwLWkIiJOI=
